import loadDirectory, { FileObject } from '@/api/server/files/loadDirectory';
import getFileContents from '@/api/server/files/getFileContents';
import saveFileContents from '@/api/server/files/saveFileContents';
import createDirectory from '@/api/server/files/createDirectory';
import http from '@/api/http';

export interface HybridAuthStatus {
    hasFastLogin: boolean;
    hasAuthMe: boolean;
    hasProtocolLib: boolean;
    hasFloodgate: boolean;
    hasSkinsRestorer: boolean;
    isOfflineMode: boolean;
    isFullyConfigured: boolean;
}

export interface HybridAuthSettings {
    mojangAutoLogin: boolean;
    bedrockAutoLogin: boolean;
    sessionCacheMinutes: number;
    minPasswordLength: number;
    maxAccountsPerIp: number;
    restoreSkins: boolean;
    serverBrandingName: string;
}

export const DEFAULT_AUTH_SETTINGS: HybridAuthSettings = {
    mojangAutoLogin: true,
    bedrockAutoLogin: true,
    sessionCacheMinutes: 60,
    minPasswordLength: 6,
    maxAccountsPerIp: 3,
    restoreSkins: true,
    serverBrandingName: 'SmitCloud',
};

export const checkHybridAuthStatus = async (uuid: string): Promise<HybridAuthStatus> => {
    let hasFastLogin = false;
    let hasAuthMe = false;
    let hasProtocolLib = false;
    let hasFloodgate = false;
    let hasSkinsRestorer = false;
    let isOfflineMode = false;

    try {
        const files: FileObject[] = await loadDirectory(uuid, '/plugins');
        hasFastLogin = files.some((f) => f.name.toLowerCase().includes('fastlogin'));
        hasAuthMe = files.some((f) => f.name.toLowerCase().includes('authme'));
        hasProtocolLib = files.some((f) => f.name.toLowerCase().includes('protocollib'));
        hasFloodgate = files.some((f) => f.name.toLowerCase().includes('floodgate'));
        hasSkinsRestorer = files.some((f) => f.name.toLowerCase().includes('skinsrestorer'));
    } catch {
        // no plugins dir
    }

    try {
        const props = await getFileContents(uuid, '/server.properties');
        isOfflineMode = /^online-mode=false/im.test(props);
    } catch {
        isOfflineMode = false;
    }

    const isFullyConfigured = hasFastLogin && hasAuthMe && hasProtocolLib && isOfflineMode;

    return {
        hasFastLogin,
        hasAuthMe,
        hasProtocolLib,
        hasFloodgate,
        hasSkinsRestorer,
        isOfflineMode,
        isFullyConfigured,
    };
};

export const installPluginJar = async (uuid: string, url: string, filename: string): Promise<void> => {
    try {
        await createDirectory(uuid, '/', 'plugins');
    } catch {
        // already exists
    }

    await http.post(`/api/client/servers/${uuid}/files/pull`, {
        url,
        directory: '/plugins',
        filename,
        use_header: true,
    });
};

export const configureServerPropertiesOfflineMode = async (uuid: string): Promise<void> => {
    try {
        let props = await getFileContents(uuid, '/server.properties');
        if (/^online-mode=.*$/m.test(props)) {
            props = props.replace(/^online-mode=.*$/m, 'online-mode=false');
        } else {
            props += '\nonline-mode=false\n';
        }
        await saveFileContents(uuid, '/server.properties', props);
    } catch {
        await saveFileContents(uuid, '/server.properties', 'online-mode=false\n');
    }
};

export const generateFastLoginConfig = (settings: HybridAuthSettings): string => {
    return `# ------------------------------------------------------------------
# FastLogin Configuration — Generated by ${settings.serverBrandingName} Hybrid Auth
# ------------------------------------------------------------------
# Automatically logs in official Mojang Java accounts without passwords
# and connects seamlessly with Bedrock Floodgate (Xbox Live).

# Enable auto login for premium Java players who own the game
autoLogin: ${settings.mojangAutoLogin}

# Automatically register verified premium players in AuthMe
autoRegister: true
auto-register-unknown: true

# Preserves official Mojang UUIDs instead of offline-mode UUIDs
premiumUuid: true

# Support Bedrock players via Floodgate (Xbox Live auto-login)
autoLoginFloodgate: ${settings.bedrockAutoLogin}
allowFloodgateNameConflict: true
autoRegisterFloodgate: ${settings.bedrockAutoLogin}
secondAttemptCracked: true

# Skin forwarding
forwardSkin: ${settings.restoreSkins}
kick-toggle: true
verifyClientKeys: false

# Database configuration
driver: 'sqlite'
database: '{pluginDir}/FastLogin.db'
`;
};

export const generateFastLoginMessages = (settings: HybridAuthSettings): string => {
    const brand = settings.serverBrandingName.toUpperCase();
    return `# FastLogin localization — ${settings.serverBrandingName} Luxury Edition
auto-login: '&b&l${brand} &8» &a✔ Official Mojang account detected! Logged in automatically.'
auto-register: '&b&l${brand} &8» &a✔ Premium account secured & registered.'
add-premium: '&b&l${brand} &8» &a✔ Added to verified premium players list.'
remove-premium: '&e&l${brand} &8» &eYou are now registered as a cracked account.'
premium-warning: '&e&l${brand} &8» &c&lWARNING: &6Only run this command if you are the owner of this official Minecraft account. Type &a/premium&6 again to confirm.'
`;
};

export const generateAuthMeConfig = (settings: HybridAuthSettings, existingYaml?: string): string => {
    if (existingYaml && existingYaml.includes('settings:')) {
        let updated = existingYaml;
        // Update session timeout
        updated = updated.replace(/timeout:\s*\d+/i, `timeout: ${settings.sessionCacheMinutes}`);
        // Enable Floodgate hook
        if (settings.bedrockAutoLogin) {
            updated = updated.replace(/floodgate:\s*false/i, 'floodgate: true');
        }
        // Allow /premium, /prem, /cracked before registration
        if (!updated.includes('/premium')) {
            updated = updated.replace(/- '\/reg'/i, "- '/reg'\n      - '/premium'\n      - '/prem'\n      - '/cracked'");
            updated = updated.replace(/- \/reg/i, "- /reg\n        - /premium\n        - /prem\n        - /cracked");
        }
        return updated;
    }

    return `# ------------------------------------------------------------------
# AuthMeReloaded Configuration — Generated by ${settings.serverBrandingName}
# ------------------------------------------------------------------
DataSource:
  backend: 'SQLITE'
  database: 'authme.db'

settings:
  security:
    minPasswordLength: ${settings.minPasswordLength}
    passwordHash: 'SHA256'
  restrictions:
    maxRegPerIp: ${settings.maxAccountsPerIp}
    maxLoginPerIp: 5
    allowMovement: false
    allowCommands:
      - '/login'
      - '/register'
      - '/l'
      - '/reg'
      - '/premium'
      - '/prem'
      - '/cracked'
  sessions:
    enabled: true
    timeout: ${settings.sessionCacheMinutes}

Hooks:
  floodgate: ${settings.bedrockAutoLogin}
  bungeecord: false
`;
};

export const applyHybridAuthSuite = async (uuid: string, settings: HybridAuthSettings): Promise<void> => {
    // 1. Configure server.properties to offline-mode=false
    await configureServerPropertiesOfflineMode(uuid);

    // 2. Install ProtocolLib (Essential for FastLogin packet interception on Paper/Spigot)
    await installPluginJar(
        uuid,
        'https://hosting.smitronix.dev/downloads/plugins/ProtocolLib.jar',
        'ProtocolLib.jar'
    );

    // 3. Install FastLogin Bukkit
    await installPluginJar(
        uuid,
        'https://hosting.smitronix.dev/downloads/plugins/FastLoginBukkit.jar',
        'FastLoginBukkit.jar'
    );

    // 4. Install AuthMe Reloaded
    await installPluginJar(
        uuid,
        'https://hosting.smitronix.dev/downloads/plugins/AuthMe-6.0.1-Spigot.jar',
        'AuthMe-6.0.1-Spigot.jar'
    );

    // 5. Install Floodgate for Bedrock Xbox Auto-Login
    if (settings.bedrockAutoLogin) {
        await installPluginJar(
            uuid,
            'https://hosting.smitronix.dev/downloads/plugins/floodgate-spigot.jar',
            'floodgate-spigot.jar'
        );
    }

    // 6. Install SkinsRestorer for universal skin display
    if (settings.restoreSkins) {
        await installPluginJar(
            uuid,
            'https://hosting.smitronix.dev/downloads/plugins/SkinsRestorer.jar',
            'SkinsRestorer.jar'
        );
    }

    // 7. Generate configuration directories & files
    try {
        await createDirectory(uuid, '/plugins', 'FastLogin');
    } catch {
        // ignore
    }

    try {
        await createDirectory(uuid, '/plugins', 'AuthMe');
    } catch {
        // ignore
    }

    const fastLoginYaml = generateFastLoginConfig(settings);
    await saveFileContents(uuid, '/plugins/FastLogin/config.yml', fastLoginYaml);

    const fastLoginMessages = generateFastLoginMessages(settings);
    await saveFileContents(uuid, '/plugins/FastLogin/messages.yml', fastLoginMessages);

    let existingAuthMe: string | undefined = undefined;
    try {
        existingAuthMe = await getFileContents(uuid, '/plugins/AuthMe/config.yml');
    } catch {
        // ignore
    }

    const authMeYaml = generateAuthMeConfig(settings, existingAuthMe);
    await saveFileContents(uuid, '/plugins/AuthMe/config.yml', authMeYaml);

    // 8. Configure AuthMe messages_en.yml with interactive premium prompt
    try {
        await createDirectory(uuid, '/plugins/AuthMe', 'messages');
    } catch {
        // ignore
    }

    try {
        let msgEn = await getFileContents(uuid, '/plugins/AuthMe/messages/messages_en.yml');
        const brand = settings.serverBrandingName.toUpperCase();
        if (!msgEn.includes('/premium')) {
            msgEn = msgEn.replace(
                /register_request:.*$/m,
                `register_request: '&8====================================================%nl%&b&l  ${brand} NETWORK &8» &fWelcome &e%username%&f!%nl%&6  Are you playing with an &a&lOFFICIAL MOJANG (PREMIUM)&6 account?%nl%&a  » &a&lPREMIUM PLAYER? &fType &b/premium &fto skip all passwords forever!%nl%&c  » &c&lCRACKED PLAYER? &fType &e/register <password> <password>%nl%&8===================================================='`
            );
            await saveFileContents(uuid, '/plugins/AuthMe/messages/messages_en.yml', msgEn);
        }
    } catch {
        // ignore
    }
};
