import loadDirectory, { FileObject } from '@/api/server/files/loadDirectory';
import getFileContents from '@/api/server/files/getFileContents';
import saveFileContents from '@/api/server/files/saveFileContents';
import createDirectory from '@/api/server/files/createDirectory';
import http from '@/api/http';

export interface HybridAuthStatus {
    hasFastLogin: boolean;
    hasAuthMe: boolean;
    hasFloodgate: boolean;
    hasSkinsRestorer: boolean;
    isOfflineMode: boolean;
    isFullyConfigured: boolean;
}

export interface HybridAuthSettings {
    mojangAutoLogin: boolean;
    bedrockAutoLogin: boolean;
    sessionCacheMinutes: number;
    minPasswordLength: number;
    maxAccountsPerIp: number;
    restoreSkins: boolean;
    serverBrandingName: string;
}

export const DEFAULT_AUTH_SETTINGS: HybridAuthSettings = {
    mojangAutoLogin: true,
    bedrockAutoLogin: true,
    sessionCacheMinutes: 60,
    minPasswordLength: 6,
    maxAccountsPerIp: 3,
    restoreSkins: true,
    serverBrandingName: 'SmitCloud',
};

export const checkHybridAuthStatus = async (uuid: string): Promise<HybridAuthStatus> => {
    let hasFastLogin = false;
    let hasAuthMe = false;
    let hasFloodgate = false;
    let hasSkinsRestorer = false;
    let isOfflineMode = false;

    try {
        const files: FileObject[] = await loadDirectory(uuid, '/plugins');
        hasFastLogin = files.some((f) => f.name.toLowerCase().includes('fastlogin'));
        hasAuthMe = files.some((f) => f.name.toLowerCase().includes('authme'));
        hasFloodgate = files.some((f) => f.name.toLowerCase().includes('floodgate'));
        hasSkinsRestorer = files.some((f) => f.name.toLowerCase().includes('skinsrestorer'));
    } catch {
        // no plugins dir
    }

    try {
        const props = await getFileContents(uuid, '/server.properties');
        isOfflineMode = /^online-mode=false/im.test(props);
    } catch {
        isOfflineMode = false;
    }

    const isFullyConfigured = hasFastLogin && hasAuthMe && isOfflineMode;

    return {
        hasFastLogin,
        hasAuthMe,
        hasFloodgate,
        hasSkinsRestorer,
        isOfflineMode,
        isFullyConfigured,
    };
};

export const installPluginJar = async (uuid: string, url: string, filename: string): Promise<void> => {
    try {
        await createDirectory(uuid, '/', 'plugins');
    } catch {
        // already exists
    }

    await http.post(`/api/client/servers/${uuid}/files/pull`, {
        url,
        directory: '/plugins',
        filename,
        use_header: true,
    });
};

export const configureServerPropertiesOfflineMode = async (uuid: string): Promise<void> => {
    try {
        let props = await getFileContents(uuid, '/server.properties');
        if (/^online-mode=.*$/m.test(props)) {
            props = props.replace(/^online-mode=.*$/m, 'online-mode=false');
        } else {
            props += '\nonline-mode=false\n';
        }
        await saveFileContents(uuid, '/server.properties', props);
    } catch {
        await saveFileContents(uuid, '/server.properties', 'online-mode=false\n');
    }
};

export const generateFastLoginConfig = (settings: HybridAuthSettings): string => {
    return `# ------------------------------------------------------------------
# FastLogin Configuration — Generated by ${settings.serverBrandingName} Hybrid Auth
# ------------------------------------------------------------------
# Automatically logs in official Mojang Java accounts without passwords
# and connects seamlessly with Bedrock Floodgate (Xbox Live).

# Enable auto login for premium Java players who own the game
autoLogin: ${settings.mojangAutoLogin}

# Automatically register verified premium players in AuthMe
autoRegister: true

# Preserves official Mojang UUIDs instead of offline-mode UUIDs
premium-uuid: true

# Support Bedrock players via Floodgate (Xbox Live auto-login)
floodgate-support: ${settings.bedrockAutoLogin}

# In-game notification messages
messages:
  auto-login: "&b&l${settings.serverBrandingName.toUpperCase()} &8» &a✔ Official Mojang account detected! Logged in automatically."
  premium-warning: "&e&l${settings.serverBrandingName.toUpperCase()} &8» &eNotice: This username is registered with Mojang."
`;
};

export const generateAuthMeConfig = (settings: HybridAuthSettings, existingYaml?: string): string => {
    if (existingYaml && existingYaml.includes('settings:')) {
        let updated = existingYaml;
        // Update session timeout
        updated = updated.replace(/timeout:\s*\d+/i, `timeout: ${settings.sessionCacheMinutes}`);
        // Enable Floodgate hook
        if (settings.bedrockAutoLogin) {
            updated = updated.replace(/floodgate:\s*false/i, 'floodgate: true');
        }
        return updated;
    }

    return `# ------------------------------------------------------------------
# AuthMeReloaded Configuration — Generated by ${settings.serverBrandingName}
# ------------------------------------------------------------------
DataSource:
  backend: 'SQLITE'
  database: 'authme.db'

settings:
  security:
    minPasswordLength: ${settings.minPasswordLength}
    passwordHash: 'SHA256'
  restrictions:
    maxRegPerIp: ${settings.maxAccountsPerIp}
    maxLoginPerIp: 5
    allowMovement: false
    allowCommands:
      - '/login'
      - '/register'
      - '/l'
      - '/reg'
  sessions:
    enabled: true
    timeout: ${settings.sessionCacheMinutes}

Hooks:
  floodgate: ${settings.bedrockAutoLogin}
  bungeecord: false
`;
};

export const applyHybridAuthSuite = async (uuid: string, settings: HybridAuthSettings): Promise<void> => {
    // 1. Configure server.properties to offline-mode=false
    await configureServerPropertiesOfflineMode(uuid);

    // 2. Install FastLogin Bukkit
    await installPluginJar(
        uuid,
        'https://github.com/TuxCoding/FastLogin/releases/download/1.12-kick-toggle/FastLoginBukkit.jar',
        'FastLoginBukkit.jar'
    );

    // 3. Install AuthMe Reloaded
    await installPluginJar(
        uuid,
        'https://github.com/AuthMe/AuthMeReloaded/releases/download/6.0.1/AuthMe-6.0.1-Spigot-1.21.jar',
        'AuthMe-6.0.1-Spigot.jar'
    );

    // 4. Install Floodgate for Bedrock Xbox Auto-Login
    if (settings.bedrockAutoLogin) {
        await installPluginJar(
            uuid,
            'https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot',
            'floodgate-spigot.jar'
        );
    }

    // 5. Install SkinsRestorer for universal skin display
    if (settings.restoreSkins) {
        await installPluginJar(
            uuid,
            'https://github.com/SkinsRestorer/SkinsRestorer/releases/download/15.12.5/SkinsRestorer.jar',
            'SkinsRestorer.jar'
        );
    }

    // 6. Generate configuration directories & files
    try {
        await createDirectory(uuid, '/plugins', 'FastLogin');
    } catch {
        // ignore
    }

    try {
        await createDirectory(uuid, '/plugins', 'AuthMe');
    } catch {
        // ignore
    }

    const fastLoginYaml = generateFastLoginConfig(settings);
    await saveFileContents(uuid, '/plugins/FastLogin/config.yml', fastLoginYaml);

    let existingAuthMe: string | undefined = undefined;
    try {
        existingAuthMe = await getFileContents(uuid, '/plugins/AuthMe/config.yml');
    } catch {
        // ignore
    }

    const authMeYaml = generateAuthMeConfig(settings, existingAuthMe);
    await saveFileContents(uuid, '/plugins/AuthMe/config.yml', authMeYaml);
};
